---
title: "honours relations 4"
author: "Ben Hamlin"
date: "2024-09-04"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#library import
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(tidyr)
library(vcd)
```


```{r}
#combine all unknown DNA sexes into 1
torea_data_berd$DNA_sex <- ifelse(torea_data_berd$DNA_sex %in% c("NO SAMPLE", "X"), "NO SAMPLE", torea_data_berd$DNA_sex)
torea_data_berd$DNA_sex[is.na(torea_data_berd$DNA_sex)] <- "NO SAMPLE"
#allows for known sex to always appear on top
torea_data_berd$alpha <- ifelse(torea_data_berd$DNA_sex %in% c("M", "F"), 1, 0.7)
#check data import 
str(torea_data_berd)
table(torea_data_berd$DNA_sex)
```

```{r}
#viewing Bill Depth compared to traits - continuous

# Bill Depth vs torea bill Width by sex
corr_test_bdbw <- cor.test(torea_data_berd$Bill_Width, torea_data_berd$Bill_Depth)
corr_coeff_bdbw <- round(corr_test_bdbw$estimate, 2)
p_value_bdbw <- corr_test_bdbw$p.value
p_value_text_bdbw <- format.pval(p_value_bdbw)

ggplot(torea_data_berd, aes(x = Bill_Width, y = Bill_Depth)) +
  geom_point(aes(color = DNA_sex,
             alpha = alpha),
size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Bill Width (mm)", y = "Bill Depth", color = "Sex", title = "Torea Bill Width vs Bill Depth") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = paste("Correlation:", corr_coeff_bdbw, "P-value:", p_value_text_bdbw),
    hjust = 1.1, vjust = 22, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Bill Depth vs torea Wing length by sex
corr_test_bdwl <- cor.test(torea_data_berd$Wing_Length, torea_data_berd$Bill_Depth)
corr_coeff_bdwl <- round(corr_test_bdwl$estimate, 2)
p_value_bdwl <- corr_test_bdwl$p.value
p_value_text_bdwl <- format.pval(p_value_bdwl)

ggplot(torea_data_berd, aes(x = Wing_Length, y = Bill_Depth)) +
  geom_point(aes(color = DNA_sex,
             alpha = alpha),
size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Wing Length (mm)", y = "Bill Depth", color = "Sex", title = "Torea wing length vs Bill Depth") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = paste("Correlation:", corr_coeff_bdwl, "P-value:", p_value_text_bdwl),
    hjust = 1.1, vjust = 22, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Bill Depth vs torea Tarsus length by sex
corr_test_bdtl <- cor.test(torea_data_berd$Tarsus_Length, torea_data_berd$Bill_Depth)
corr_coeff_bdtl <- round(corr_test_bdtl$estimate, 2)
p_value_bdtl <- corr_test_bdtl$p.value
p_value_text_bdtl <- format.pval(p_value_bdtl)

ggplot(torea_data_berd, aes(x = Tarsus_Length, y = Bill_Depth)) +
  geom_point(aes(color = DNA_sex,
             alpha = alpha),
size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Tarsus Length (mm)", y = "Bill Depth", color = "Sex", title = "Torea tarsus length vs Bill Depth") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = paste("Correlation:", corr_coeff_bdtl, "P-value:", p_value_text_bdtl),
    hjust = 1.1, vjust = 22, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Bill Depth vs torea body condition by sex
corr_test_bdbc <- cor.test(torea_data_berd$Body_condition_TL, torea_data_berd$Bill_Depth)
corr_coeff_bdbc <- round(corr_test_bdbc$estimate, 2)
p_value_bdbc <- corr_test_bdbc$p.value
p_value_text_bdbc <- format.pval(p_value_bdbc)

ggplot(torea_data_berd, aes(x = Body_condition_TL, y = Bill_Depth)) +
  geom_point(aes(color = DNA_sex,
             alpha = alpha),
size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Body Condition", y = "Bill Depth", color = "Sex", title = "Torea body condition vs Bill Depth") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = paste("Correlation:", corr_coeff_bdbc, "P-value:", p_value_text_bdbc),
    hjust = 1.1, vjust = 22, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# assessing body condition compared to categorical variables

# Bill Depth vs bill colour by sex
torea_data_berd_vis1 <- torea_data_berd %>%
  filter(!is.na(Bill_Colour))
torea_data_berd_vis1$Bill_Colour <- as.factor(torea_data_berd_vis1$Bill_Colour)

anova_bdbc <- aov(Bill_Depth ~ Bill_Colour, data = torea_data_berd_vis1)
anova_sum_bdbc <- summary(anova_bdbc)[[1]]
p_value_bdbc <- anova_sum_bdbc["Bill_Colour", "Pr(>F)"]
f_value_bdbc <- anova_sum_wbc["Bill_Colour", "F value"]
anova_text_bdbc <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_bdbc, 2), "\n",
  "p-value = ", format.pval(p_value_bdbc)
)

ggplot(torea_data_berd_vis1, aes(x = Bill_Colour, y = Bill_Depth)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Bill Colour", y = "Bill Depth", color = "Sex", title = "Torea bill colour vs Bill Depth") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_bdbc,
    hjust = 1.1, vjust = 5, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Bill Depth vs leg colour by sex
torea_data_berd_vis2 <- torea_data_berd %>%
  filter(!is.na(Leg_Colour))
torea_data_berd_vis2$Leg_Colour <- as.factor(torea_data_berd_vis2$Leg_Colour)

anova_bdlc <- aov(Bill_Depth ~ Leg_Colour, data = torea_data_berd_vis2)
anova_sum_bdlc <- summary(anova_bdlc)[[1]]
p_value_bdlc <- anova_sum_bdlc["Leg_Colour", "Pr(>F)"]
f_value_bdlc <- anova_sum_bdlc["Leg_Colour", "F value"]
anova_text_bdlc <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_bdlc, 2), "\n",
  "p-value = ", format.pval(p_value_bdlc)
)

ggplot(torea_data_berd_vis2, aes(x = Leg_Colour, y = Bill_Depth)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Leg Colour", y = "Bill Depth", color = "Sex", title = "Torea leg colour vs Bill Depth") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_bdlc,
    hjust = 1.1, vjust = 5, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Bill Depth vs Iris colour by sex
torea_data_berd_vis3 <- torea_data_berd %>%
  filter(!is.na(Iris_Colour))
torea_data_berd_vis3$Iris_Colour <- as.factor(torea_data_berd_vis3$Iris_Colour)

anova_bdic <- aov(Bill_Depth ~ Iris_Colour, data = torea_data_berd_vis3)
anova_sum_bdic <- summary(anova_bdic)[[1]]
p_value_bdic <- anova_sum_bdic["Iris_Colour", "Pr(>F)"]
f_value_bdic <- anova_sum_bdic["Iris_Colour", "F value"]
anova_text_bdic <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_bdic, 2), "\n",
  "p-value = ", format.pval(p_value_bdic)
)

ggplot(torea_data_berd_vis3, aes(x = Iris_Colour, y = Bill_Depth)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Iris Colour", y = "Bill Depth", color = "Sex", title = "Torea iris colour vs Bill Depth") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_bdic,
    hjust = 1.1, vjust = 5.3, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Bill Depth vs iris fleck by sex
torea_data_berd_vis4 <- torea_data_berd %>%
  filter(!is.na(Iris_Fleck))
torea_data_berd_vis4$Iris_Fleck <- as.factor(torea_data_berd_vis4$Iris_Fleck)

anova_bdif <- aov(Bill_Depth ~ Iris_Fleck, data = torea_data_berd_vis4)
anova_sum_bdif <- summary(anova_bdif)[[1]]
p_value_bdif <- anova_sum_bdif["Iris_Fleck", "Pr(>F)"]
f_value_bdif <- anova_sum_bdif["Iris_Fleck", "F value"]
anova_text_bdif <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_bdif, 2), "\n",
  "p-value = ", format.pval(p_value_bdif)
)

ggplot(torea_data_berd_vis4, aes(x = Iris_Fleck, y = Bill_Depth)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Iris Fleck", y = "Bill Depth", color = "Sex", title = "Torea iris fleck vs Bill Depth") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_bdif,
    hjust = 1.1, vjust = 5, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

```