---
title: "comparative tables"
author: "Ben Hamlin"
date: "2024-09-04"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#library import
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(tidyr)
library(vcd)
```


```{r}
#combine all unknown DNA sexes into 1
torea_data_berd$DNA_sex <- ifelse(torea_data_berd$DNA_sex %in% c("NO SAMPLE", "X"), "NO SAMPLE", torea_data_berd$DNA_sex)
torea_data_berd$DNA_sex[is.na(torea_data_berd$DNA_sex)] <- "NO SAMPLE"
#allows for known sex to always appear on top
torea_data_berd$alpha <- ifelse(torea_data_berd$DNA_sex %in% c("M", "F"), 1, 0.7)
#check data import 
str(torea_data_berd)
table(torea_data_berd$DNA_sex)
```

```{r}
#viewing weight compared to traits - continuous

# weight vs torea bill length by sex
corr_test_wbl <- cor.test(torea_data_berd$Bill_Length, torea_data_berd$Weight)
corr_coeff_wbl <- round(corr_test_wbl$estimate, 2)
p_value_wbl <- corr_test_wbl$p.value
p_value_text_wbl <- format.pval(p_value_wbl)

ggplot(torea_data_berd, aes(x = Bill_Length, y = Weight)) +
  geom_point(aes(color = DNA_sex,
             alpha = alpha),
size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Bill Length (mm)", y = "Torea Weight (g)", color = "Sex", title = "Torea Bill Length vs Weight") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = paste("Correlation:", corr_coeff_wbl, "P-value:", p_value_text_wbl),
    hjust = 1.1, vjust = 22, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# weight vs torea bill depth by sex
corr_test_wbd <- cor.test(torea_data_berd$Bill_Depth, torea_data_berd$Weight)
corr_coeff_wbd <- round(corr_test_wbd$estimate, 2)
p_value_wbd <- corr_test_wbd$p.value
p_value_text_wbd <- format.pval(p_value_wbd)

ggplot(torea_data_berd, aes(x = Bill_Depth, y = Weight)) +
  geom_point(aes(color = DNA_sex,
             alpha = alpha),
size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Bill Depth (mm)", y = "Torea Weight (g)", color = "Sex", title = "Torea Bill Depth vs weight") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = paste("Correlation:", corr_coeff_wbd, "P-value:", p_value_text_wbd),
    hjust = 1.1, vjust = 22, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# weight vs torea bill Width by sex
corr_test_wbw <- cor.test(torea_data_berd$Bill_Width, torea_data_berd$Weight)
corr_coeff_wbw <- round(corr_test_wbw$estimate, 2)
p_value_wbw <- corr_test_wbw$p.value
p_value_text_wbw <- format.pval(p_value_wbw)

ggplot(torea_data_berd, aes(x = Bill_Width, y = Weight)) +
  geom_point(aes(color = DNA_sex,
             alpha = alpha),
size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Bill Width (mm)", y = "Weight", color = "Sex", title = "Torea Bill Width vs Weight") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = paste("Correlation:", corr_coeff_wbw, "P-value:", p_value_text_wbw),
    hjust = 1.1, vjust = 22, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Weight vs torea Wing length by sex
corr_test_wwl <- cor.test(torea_data_berd$Wing_Length, torea_data_berd$Weight)
corr_coeff_wwl <- round(corr_test_wwl$estimate, 2)
p_value_wwl <- corr_test_wwl$p.value
p_value_text_wwl <- format.pval(p_value_wwl)

ggplot(torea_data_berd, aes(x = Wing_Length, y = Weight)) +
  geom_point(aes(color = DNA_sex,
             alpha = alpha),
size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Wing Length (mm)", y = "Weight", color = "Sex", title = "Torea wing length vs Weight") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = paste("Correlation:", corr_coeff_wwl, "P-value:", p_value_text_wwl),
    hjust = 1.1, vjust = 22, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Weight vs torea Tarsus length by sex
corr_test_wtl <- cor.test(torea_data_berd$Tarsus_Length, torea_data_berd$Weight)
corr_coeff_wtl <- round(corr_test_wtl$estimate, 2)
p_value_wtl <- corr_test_wtl$p.value
p_value_text_wtl <- format.pval(p_value_wtl)

ggplot(torea_data_berd, aes(x = Tarsus_Length, y = Weight)) +
  geom_point(aes(color = DNA_sex,
             alpha = alpha),
size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Tarsus Length (mm)", y = "Weight", color = "Sex", title = "Torea tarsus length vs Weight") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = paste("Correlation:", corr_coeff_wtl, "P-value:", p_value_text_wtl),
    hjust = 1.1, vjust = 22, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Weight vs torea body condition by sex
corr_test_wbc <- cor.test(torea_data_berd$Body_condition_TL, torea_data_berd$Weight)
corr_coeff_wbc <- round(corr_test_wbc$estimate, 2)
p_value_wbc <- corr_test_wbc$p.value
p_value_text_wbc <- format.pval(p_value_wbc)

ggplot(torea_data_berd, aes(x = Body_condition_TL, y = Weight)) +
  geom_point(aes(color = DNA_sex,
             alpha = alpha),
size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Body Condition", y = "Weight", color = "Sex", title = "Torea body condition vs Weight") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = paste("Correlation:", corr_coeff_wbc, "P-value:", p_value_text_wbc),
    hjust = 1.1, vjust = 22, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# assessing body condition compared to categorical variables

# Weight vs bill colour by sex
torea_data_berd_vis1 <- torea_data_berd %>%
  filter(!is.na(Bill_Colour))
torea_data_berd_vis1$Bill_Colour <- as.factor(torea_data_berd_vis1$Bill_Colour)

anova_wbc <- aov(Weight ~ Bill_Colour, data = torea_data_berd_vis1)
anova_sum_wbc <- summary(anova_wbc)[[1]]
p_value_wbc <- anova_sum_wbc["Bill_Colour", "Pr(>F)"]
f_value_wbc <- anova_sum_wbc["Bill_Colour", "F value"]
anova_text_wbc <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_wbc, 2), "\n",
  "p-value = ", format.pval(p_value_wbc)
)

ggplot(torea_data_berd_vis1, aes(x = Bill_Colour, y = Weight)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Bill Colour", y = "Weight", color = "Sex", title = "Torea bill colour vs Weight") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_wbc,
    hjust = 1.1, vjust = 5, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Weight vs leg colour by sex
torea_data_berd_vis2 <- torea_data_berd %>%
  filter(!is.na(Leg_Colour))
torea_data_berd_vis2$Leg_Colour <- as.factor(torea_data_berd_vis2$Leg_Colour)

anova_wlc <- aov(Weight ~ Leg_Colour, data = torea_data_berd_vis2)
anova_sum_wlc <- summary(anova_wlc)[[1]]
p_value_wlc <- anova_sum_wlc["Leg_Colour", "Pr(>F)"]
f_value_wlc <- anova_sum_wlc["Leg_Colour", "F value"]
anova_text_wlc <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_wlc, 2), "\n",
  "p-value = ", format.pval(p_value_wlc)
)

ggplot(torea_data_berd_vis2, aes(x = Leg_Colour, y = Weight)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Leg Colour", y = "Weight", color = "Sex", title = "Torea leg colour vs Weight") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_wlc,
    hjust = 1.1, vjust = 5, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Weight vs Iris colour by sex
torea_data_berd_vis3 <- torea_data_berd %>%
  filter(!is.na(Iris_Colour))
torea_data_berd_vis3$Iris_Colour <- as.factor(torea_data_berd_vis3$Iris_Colour)

anova_wic <- aov(Weight ~ Iris_Colour, data = torea_data_berd_vis3)
anova_sum_wic <- summary(anova_wic)[[1]]
p_value_wic <- anova_sum_wic["Iris_Colour", "Pr(>F)"]
f_value_wic <- anova_sum_wic["Iris_Colour", "F value"]
anova_text_wic <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_wic, 2), "\n",
  "p-value = ", format.pval(p_value_wic)
)

ggplot(torea_data_berd_vis3, aes(x = Iris_Colour, y = Weight)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Iris Colour", y = "Weight", color = "Sex", title = "Torea iris colour vs Weight") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_wic,
    hjust = 1.1, vjust = 5.3, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Weight vs iris fleck by sex
torea_data_berd_vis4 <- torea_data_berd %>%
  filter(!is.na(Iris_Fleck))
torea_data_berd_vis4$Iris_Fleck <- as.factor(torea_data_berd_vis4$Iris_Fleck)

anova_wif <- aov(Weight ~ Iris_Fleck, data = torea_data_berd_vis4)
anova_sum_wif <- summary(anova_wif)[[1]]
p_value_wif <- anova_sum_wif["Iris_Fleck", "Pr(>F)"]
f_value_wif <- anova_sum_wif["Iris_Fleck", "F value"]
anova_text_wif <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_wif, 2), "\n",
  "p-value = ", format.pval(p_value_wif)
)

ggplot(torea_data_berd_vis4, aes(x = Iris_Fleck, y = Weight)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Iris Fleck", y = "Weight", color = "Sex", title = "Torea iris fleck vs Weight") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_wif,
    hjust = 1.1, vjust = 5, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

```
