---
title: "Honours relations 7"
author: "Ben Hamlin"
date: "2024-09-04"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#library import
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(tidyr)
library(vcd)
```


```{r}
#combine all unknown DNA sexes into 1
torea_data_berd$DNA_sex <- ifelse(torea_data_berd$DNA_sex %in% c("NO SAMPLE", "X"), "NO SAMPLE", torea_data_berd$DNA_sex)
torea_data_berd$DNA_sex[is.na(torea_data_berd$DNA_sex)] <- "NO SAMPLE"
#allows for known sex to always appear on top
torea_data_berd$alpha <- ifelse(torea_data_berd$DNA_sex %in% c("M", "F"), 1, 0.7)
#check data import 
str(torea_data_berd)
table(torea_data_berd$DNA_sex)
```

```{r}
#viewing Tarsus Length compared to traits - continuous

# Tarsus Length vs torea body condition by sex
corr_test_tlbc <- cor.test(torea_data_berd$Body_condition_TL, torea_data_berd$Tarsus_Length)
corr_coeff_tlbc <- round(corr_test_tlbc$estimate, 2)
p_value_tlbc <- corr_test_tlbc$p.value
p_value_text_tlbc <- format.pval(p_value_tlbc)

ggplot(torea_data_berd, aes(x = Body_condition_TL, y = Tarsus_Length)) +
  geom_point(aes(color = DNA_sex,
             alpha = alpha),
size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Body Condition", y = "Tarsus Length", color = "Sex", title = "Torea body condition vs Tarsus Length") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = paste("Correlation:", corr_coeff_tlbc, "P-value:", p_value_text_tlbc),
    hjust = 1.1, vjust = 24, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# assessing body condition compared to categorical variables

# Tarsus Length vs bill colour by sex
torea_data_berd_vis1 <- torea_data_berd %>%
  filter(!is.na(Bill_Colour))
torea_data_berd_vis1$Bill_Colour <- as.factor(torea_data_berd_vis1$Bill_Colour)

anova_tlbc <- aov(Tarsus_Length ~ Bill_Colour, data = torea_data_berd_vis1)
anova_sum_tlbc <- summary(anova_tlbc)[[1]]
p_value_tlbc <- anova_sum_tlbc["Bill_Colour", "Pr(>F)"]
f_value_tlbc <- anova_sum_wbc["Bill_Colour", "F value"]
anova_text_tlbc <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_tlbc, 2), "\n",
  "p-value = ", format.pval(p_value_tlbc)
)

ggplot(torea_data_berd_vis1, aes(x = Bill_Colour, y = Tarsus_Length)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Bill Colour", y = "Tarsus Length", color = "Sex", title = "Torea bill colour vs Tarsus Length") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_tlbc,
    hjust = 1.1, vjust = 5, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Tarsus Length vs leg colour by sex
torea_data_berd_vis2 <- torea_data_berd %>%
  filter(!is.na(Leg_Colour))
torea_data_berd_vis2$Leg_Colour <- as.factor(torea_data_berd_vis2$Leg_Colour)

anova_tllc <- aov(Tarsus_Length ~ Leg_Colour, data = torea_data_berd_vis2)
anova_sum_tllc <- summary(anova_tllc)[[1]]
p_value_tllc <- anova_sum_tllc["Leg_Colour", "Pr(>F)"]
f_value_tllc <- anova_sum_tllc["Leg_Colour", "F value"]
anova_text_tllc <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_tllc, 2), "\n",
  "p-value = ", format.pval(p_value_tllc)
)

ggplot(torea_data_berd_vis2, aes(x = Leg_Colour, y = Tarsus_Length)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Leg Colour", y = "Tarsus Length", color = "Sex", title = "Torea leg colour vs Tarsus Length") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_tllc,
    hjust = 1.1, vjust = 5, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Tarsus Length vs Iris colour by sex
torea_data_berd_vis3 <- torea_data_berd %>%
  filter(!is.na(Iris_Colour))
torea_data_berd_vis3$Iris_Colour <- as.factor(torea_data_berd_vis3$Iris_Colour)

anova_tlic <- aov(Tarsus_Length ~ Iris_Colour, data = torea_data_berd_vis3)
anova_sum_tlic <- summary(anova_tlic)[[1]]
p_value_tlic <- anova_sum_tlic["Iris_Colour", "Pr(>F)"]
f_value_tlic <- anova_sum_tlic["Iris_Colour", "F value"]
anova_text_tlic <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_tlic, 2), "\n",
  "p-value = ", format.pval(p_value_tlic)
)

ggplot(torea_data_berd_vis3, aes(x = Iris_Colour, y = Tarsus_Length)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Iris Colour", y = "Tarsus Length", color = "Sex", title = "Torea iris colour vs Tarsus Length") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_tlic,
    hjust = 1.1, vjust = 5.3, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Tarsus Length vs iris fleck by sex
torea_data_berd_vis4 <- torea_data_berd %>%
  filter(!is.na(Iris_Fleck))
torea_data_berd_vis4$Iris_Fleck <- as.factor(torea_data_berd_vis4$Iris_Fleck)

anova_tlif <- aov(Tarsus_Length ~ Iris_Fleck, data = torea_data_berd_vis4)
anova_sum_tlif <- summary(anova_tlif)[[1]]
p_value_tlif <- anova_sum_tlif["Iris_Fleck", "Pr(>F)"]
f_value_tlif <- anova_sum_tlif["Iris_Fleck", "F value"]
anova_text_tlif <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_tlif, 2), "\n",
  "p-value = ", format.pval(p_value_tlif)
)

ggplot(torea_data_berd_vis4, aes(x = Iris_Fleck, y = Tarsus_Length)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Iris Fleck", y = "Tarsus Length", color = "Sex", title = "Torea iris fleck vs Tarsus Length") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_tlif,
    hjust = 1.1, vjust = 5, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

```