---
title: "honours relation 6"
author: "Ben Hamlin"
date: "2024-09-04"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#library import
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(tidyr)
library(vcd)
```


```{r}
#combine all unknown DNA sexes into 1
torea_data_berd$DNA_sex <- ifelse(torea_data_berd$DNA_sex %in% c("NO SAMPLE", "X"), "NO SAMPLE", torea_data_berd$DNA_sex)
torea_data_berd$DNA_sex[is.na(torea_data_berd$DNA_sex)] <- "NO SAMPLE"
#allows for known sex to always appear on top
torea_data_berd$alpha <- ifelse(torea_data_berd$DNA_sex %in% c("M", "F"), 1, 0.7)
#check data import 
str(torea_data_berd)
table(torea_data_berd$DNA_sex)
```

```{r}
#viewing Wing Length compared to traits - continuous

# Wing Length vs torea Tarsus length by sex
corr_test_wltl <- cor.test(torea_data_berd$Tarsus_Length, torea_data_berd$Wing_Length)
corr_coeff_wltl <- round(corr_test_wltl$estimate, 2)
p_value_wltl <- corr_test_wltl$p.value
p_value_text_wltl <- format.pval(p_value_wltl)

ggplot(torea_data_berd, aes(x = Tarsus_Length, y = Wing_Length)) +
  geom_point(aes(color = DNA_sex,
             alpha = alpha),
size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Tarsus Length (mm)", y = "Wing Length", color = "Sex", title = "Torea tarsus length vs Wing Length") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = paste("Correlation:", corr_coeff_wltl, "P-value:", p_value_text_wltl),
    hjust = 1.1, vjust = 24, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Wing Length vs torea body condition by sex
corr_test_wlbc <- cor.test(torea_data_berd$Body_condition_TL, torea_data_berd$Wing_Length)
corr_coeff_wlbc <- round(corr_test_wlbc$estimate, 2)
p_value_wlbc <- corr_test_wlbc$p.value
p_value_text_wlbc <- format.pval(p_value_wlbc)

ggplot(torea_data_berd, aes(x = Body_condition_TL, y = Wing_Length)) +
  geom_point(aes(color = DNA_sex,
             alpha = alpha),
size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Body Condition", y = "Wing Length", color = "Sex", title = "Torea body condition vs Wing Length") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = paste("Correlation:", corr_coeff_wlbc, "P-value:", p_value_text_wlbc),
    hjust = 1.1, vjust = 24, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# assessing body condition compared to categorical variables

# Wing Length vs bill colour by sex
torea_data_berd_vis1 <- torea_data_berd %>%
  filter(!is.na(Bill_Colour))
torea_data_berd_vis1$Bill_Colour <- as.factor(torea_data_berd_vis1$Bill_Colour)

anova_wlbc <- aov(Wing_Length ~ Bill_Colour, data = torea_data_berd_vis1)
anova_sum_wlbc <- summary(anova_wlbc)[[1]]
p_value_wlbc <- anova_sum_wlbc["Bill_Colour", "Pr(>F)"]
f_value_wlbc <- anova_sum_wbc["Bill_Colour", "F value"]
anova_text_wlbc <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_wlbc, 2), "\n",
  "p-value = ", format.pval(p_value_wlbc)
)

ggplot(torea_data_berd_vis1, aes(x = Bill_Colour, y = Wing_Length)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Bill Colour", y = "Wing Length", color = "Sex", title = "Torea bill colour vs Wing Length") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_wlbc,
    hjust = 1.1, vjust = 5, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Wing Length vs leg colour by sex
torea_data_berd_vis2 <- torea_data_berd %>%
  filter(!is.na(Leg_Colour))
torea_data_berd_vis2$Leg_Colour <- as.factor(torea_data_berd_vis2$Leg_Colour)

anova_wllc <- aov(Wing_Length ~ Leg_Colour, data = torea_data_berd_vis2)
anova_sum_wllc <- summary(anova_wllc)[[1]]
p_value_wllc <- anova_sum_wllc["Leg_Colour", "Pr(>F)"]
f_value_wllc <- anova_sum_wllc["Leg_Colour", "F value"]
anova_text_wllc <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_wllc, 2), "\n",
  "p-value = ", format.pval(p_value_wllc)
)

ggplot(torea_data_berd_vis2, aes(x = Leg_Colour, y = Wing_Length)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Leg Colour", y = "Wing Length", color = "Sex", title = "Torea leg colour vs Wing Length") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_wllc,
    hjust = 1.1, vjust = 5, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Wing Length vs Iris colour by sex
torea_data_berd_vis3 <- torea_data_berd %>%
  filter(!is.na(Iris_Colour))
torea_data_berd_vis3$Iris_Colour <- as.factor(torea_data_berd_vis3$Iris_Colour)

anova_wlic <- aov(Wing_Length ~ Iris_Colour, data = torea_data_berd_vis3)
anova_sum_wlic <- summary(anova_wlic)[[1]]
p_value_wlic <- anova_sum_wlic["Iris_Colour", "Pr(>F)"]
f_value_wlic <- anova_sum_wlic["Iris_Colour", "F value"]
anova_text_wlic <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_wlic, 2), "\n",
  "p-value = ", format.pval(p_value_wlic)
)

ggplot(torea_data_berd_vis3, aes(x = Iris_Colour, y = Wing_Length)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Iris Colour", y = "Wing Length", color = "Sex", title = "Torea iris colour vs Wing Length") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_wlic,
    hjust = 1.1, vjust = 5.3, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

# Wing Length vs iris fleck by sex
torea_data_berd_vis4 <- torea_data_berd %>%
  filter(!is.na(Iris_Fleck))
torea_data_berd_vis4$Iris_Fleck <- as.factor(torea_data_berd_vis4$Iris_Fleck)

anova_wlif <- aov(Wing_Length ~ Iris_Fleck, data = torea_data_berd_vis4)
anova_sum_wlif <- summary(anova_wlif)[[1]]
p_value_wlif <- anova_sum_wlif["Iris_Fleck", "Pr(>F)"]
f_value_wlif <- anova_sum_wlif["Iris_Fleck", "F value"]
anova_text_wlif <- paste(
  "ANOVA:\n",
  "F = ", round(f_value_wlif, 2), "\n",
  "p-value = ", format.pval(p_value_wlif)
)

ggplot(torea_data_berd_vis4, aes(x = Iris_Fleck, y = Wing_Length)) +
  geom_jitter(aes(color = DNA_sex,
             alpha = alpha),
width = 0.2, size = 3) +
  scale_color_manual(values = c("M" = "blue", "F" = "red", "NO SAMPLE" = "grey")) +
  scale_alpha_identity(guide = "none") +
  labs(x = "Torea Iris Fleck", y = "Wing Length", color = "Sex", title = "Torea iris fleck vs Wing Length") +
   annotate(
    "text", 
    x = Inf, y = Inf, 
    label = anova_text_wlif,
    hjust = 1.1, vjust = 5, size = 4,  color = "black", fontface = "italic") +
  theme_minimal() +
  theme(legend.position = "top")

```